version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: glow_postgres
    restart: always

    environment:
      POSTGRES_DB: glow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: glow_backend

    restart: always

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      - postgres

    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: